name: OkwSquadAdd
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Mod
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mod
          path: build/libs/mod.jar